#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Jakub Staroń, 2016

import argparse
import os
import codecs
import re
from collections import deque


def directory_of_file(filename):
    return os.path.dirname(os.path.realpath(filename))


def load_lines(filename):
    with codecs.open(filename, "r", "utf-8") as file:
        lines = [line for line in file]
        return lines

def is_pragma(line):
    return re.match("^#pragma\s+once", line) is not None

def is_local_input(line):
    return re.match("^#include\s+\"(.*)\"", line) is not None

def is_copyright_comment(line):
    return re.match("//\s+Jakub\s+Staroń", line) is not None


class FileIncluder:
    def __init__(self, path):
        self.path = path
        self.loaded = set()

    def load(self, line):
        include = self.get_include_name(line)
        if include not in self.loaded:
            self.loaded.add(include)
            return load_lines(os.path.join(self.path, include))
        else:
            return list()

    def get_include_name(self, line):
        match = re.match("^#include\s+\"(.*)\"", line)
        return match.group(1)


def copyright_message():
    message = (
        u'// Generated by include.py\n'
        u'// Jakub Staroń, 2016\n'
        u'// For more info see https://github.com/staronj/ProgrammingContestsLibrary\n'
    )
    return message

def main():
    parser = argparse.ArgumentParser(description='Generate random passwords.')
    parser.add_argument('--input', required=True, type=str, help='name of input file')
    parser.add_argument('--output', required=True, type=str, help='name of output file, must be different from input')
    parser.add_argument('--path', required=False, type=str, help='path with PCL library, default is input file folder')

    args = parser.parse_args()
    if args.path is None:
        args.path = directory_of_file(args.input)

    if args.input == args.output:
        parser.print_help()
        exit(1)

    queue = deque()
    queue.extend(load_lines(args.input))

    includer = FileIncluder(args.path)

    with codecs.open(args.output, "w", "utf-8") as file:
        file.write(copyright_message())
        while queue:
            line = queue.popleft()
            if is_pragma(line) or is_copyright_comment(line):
                continue
            elif is_local_input(line):
                lines = includer.load(line)
                queue.extendleft(reversed(lines))
            else:
                file.write(line)


if __name__ == "__main__":
    main()
